---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: go-compile
    type: builder
    artifact_dir: ./
    build_type: shell
    script: |-
      #!/bin/bash
      wget https://raw.githubusercontent.com/canha/golang-tools-install-script/28fb3d63e3746acfa624d28395a0df3e0f9fca1e/goinstall.sh >/dev/null 2>&1
      bash goinstall.sh --64
      source $HOME/.profile
      make
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: go-compile
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push
      # view logs
      #cf logs "${CF_APP}" --recent
